repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/ORCID/pre-commit-spotless
    rev: v1.0.0
    hooks:
      - id: spotless-check
        types_or: [java]
      - id: spotless-apply
        types_or: [java]
