---
name: Crowdin

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  actions: write
  contents: write
  pull-requests: write

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: crowdin action
        uses: crowdin/github-action@8f01d54f70f1713ee3f09d82c2bbb2daeac28689 # v2
        with:
          upload_translations: true
          download_translations: true
          skip_untranslated_files: true
          auto_approve_imported: true
          push_translations: true
          export_only_approved: true
          commit_message: 'New Crowdin translations'
          create_pull_request: true
          pull_request_title: 'Update localization'
          pull_request_labels: 'localization'
          base_url: 'https://jenkins.crowdin.com'
          config: 'crowdin.yml'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID:  35
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
